# Generated by Django 5.1.7 on 2025-05-11 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professions',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
        migrations.AddField(
            model_name='professions',
            name='demand',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Востребованность профессии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professions',
            name='exams',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Предметы ЕГЭ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professions',
            name='studying',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Направления обучения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professions',
            name='unis',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Вузы'),
            preserve_default=False,
        ),
    ]
